
program ::= expression_list ;;

expression_list ::= expression expression_list ;;

expression ::= 
    '\''? list
    ;;

list ::= '(' atoms ')' ;;

atoms ::= atom+ ;;

atom ::= Symbol
    | Number
    | String
    ;;
