location
	= ID[.ID]*
	| STRING
	;

value
	= STRING
	| NUMBER
	; 

stmt
	= SELECT location FROM location [WHERE expr]
	| INSERT INTO location '(' location [',' location] ')'  VALUES '(' value [, value]* ')'
	;

expr
	= factor [('+' | '-' | '*' | '/' ) expr]*
	;


unary_op 
	= ['-' | '+' ] NUMBER
	;

factor  
	= ID 
	| NUMBER
	| unary_op
	| "(" expression ")"
    | ID '(' [expr [',' expr]*] ')'
	;
